services:
  eventure-frontend:
    build: ../eventure-frontend/.
    ports:
      - "4000:80"
  eventure-node:
    build: ../eventure-node/.
    ports:
      - "8000:8000"
  eventure-java:
    build: ../eventure-java/.
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m










